name: chaji
region: ams
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: REPLACE_WITH_YOUR/REPO
      branch: main
      deploy_on_push: true
    http_port: 3333
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
      - key: SESSION_SECRET
        type: SECRET
        scope: RUN_TIME
      - key: ANTHROPIC_API_KEY
        type: SECRET
        scope: RUN_TIME
databases:
  - name: db
    engine: PG
    version: "16"
    production: false
    cluster_name: chaji-db
